// Type definitions for yopl — solver core.
// Generated by hand from src/solve.js.

import type {Env, Variable} from 'deep6/env.js';

/**
 * A goal: either a structured term, a bare goal name, or an inline JS
 * function executed during proof search.
 */
export type Goal = string | TermObject | GoalFn;

/**
 * Structured goal term. `name` is the rule name (omitted for the rule
 * head, where only `args` matters). `args` is the argument vector that
 * unifies against the head of a rule.
 */
export interface TermObject {
  name?: string;
  args?: readonly unknown[];
}

/**
 * Inline goal function executed by the solver.
 *
 * Receives the current environment, the current goal frame, and the
 * driver stack (mutable — control-flow predicates like `cut` and `halt`
 * splice or rewrite frames). Return values:
 *  - `true`     — succeed and advance to the next goal
 *  - `false`    — fail and trigger backtracking
 *  - `null`     — succeed and continue with the current goal frame as-is
 *                 (useful for mid-rule control predicates that don't
 *                 introduce new goals)
 *  - a goal frame — replace the current continuation
 */
export type GoalFn = (env: Env, goals: GoalFrame, stack: unknown[]) => boolean | GoalFrame | null | void;

/**
 * Async variant of `GoalFn` accepted by `solvers/async.js` and
 * `solvers/asyncGen.js`. The proof loop in those drivers `await`s the
 * return value, so a goal function may return any of `GoalFn`'s shapes
 * directly or as a promise.
 */
export type AsyncGoalFn = (env: Env, goals: GoalFrame, stack: unknown[]) => boolean | GoalFrame | null | void | Promise<boolean | GoalFrame | null | void>;

/** Linked list of goal frames maintained by the prover. */
export interface GoalFrame {
  terms: ReadonlyArray<Goal>;
  index: number;
  next: GoalFrame | null;
}

/**
 * A rule body factory. Receives a fresh batch of logical variables and
 * returns the rule's terms; the first element is the head and the rest
 * are body goals.
 */
export type RuleBody = (...vars: Variable[]) => ReadonlyArray<Goal>;

/** A single rule body or a disjunction (an array of bodies). */
export type Rule = RuleBody | ReadonlyArray<RuleBody>;

/** Rule database — maps a rule name to its definition. */
export type Rules = Record<string, Rule>;

/** Callback invoked once per solution discovered by the solver. */
export type SolveCallback = (env: Env) => void;

/**
 * Run the callback-style solver against `rules`, attempting to satisfy
 * the goal named `name` with the supplied `args`. The callback fires
 * once for every solution found.
 *
 * @param rules    Rule database.
 * @param name     Initial goal name.
 * @param args     Argument vector for the initial goal.
 * @param callback Invoked for every solution.
 */
declare function solve(rules: Rules, name: string, args: ReadonlyArray<unknown>, callback: SolveCallback): void;

export default solve;
export {solve};
